### ISSUE TITLE
Use logger instead of stdout

### ISSUE THREAD

**Issue by lpil** [Cyteon/discord_gleam#1]
Hello!

The BEAM has a very sophisticated logger, but this library uses stdout instead. It would be great to use the logger so users of this library can take advantage of all of its capabilities and performance advantages.

Thanks!

**Comment by luq-mn** [comment]
Hello there, my friend here is really shocked to see you here opening an issue. 
Thanks for your time.

**Comment by Cyteon** [comment]
😭

**Comment by Cyteon** [comment]
Thanks for letting me know, ill take a look at this

**Comment by lpil** [comment]
💜 💜 💜 💜 💜

**Comment by Cyteon** [comment]
Do you happen to have a link to docs for this, im not able to find anything that can help me.

**Comment by patrik-kuehl** [comment]
The package you're looking for is [logging](https://hexdocs.pm/logging/).

**Comment by Cyteon** [comment]
Now using https://hexdocs.pm/logging/
